/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MeController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletsController_list"];
        put?: never;
        post: operations["WalletsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthDto: {
            /** @enum {string} */
            status: "ok";
        };
        ErrorResponseDto: {
            /** @enum {string} */
            code: "BAD_REQUEST" | "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND_OR_NOT_OWNED" | "IDEMPOTENCY_CONFLICT" | "CONCURRENT_UPDATE" | "RATE_LIMITED" | "NOT_IMPLEMENTED" | "INTERNAL_ERROR" | "WALLET_CURRENCY_NOT_ALLOWED" | "CREDIT_NOT_VALID_FOR_SALARY_DESTINATION" | "BANK_REQUIRED" | "UNKNOWN_BILLING_PERIOD" | "INSUFFICIENT_KNOWN_BALANCE" | "DUE_OVERALLOCATED" | "FX_RATE_REQUIRED" | "LOAN_RECONCILIATION_REQUIRED" | "FORECAST_NOT_ACTUAL" | "BUDGET_CURRENCY_MISMATCH";
            message: string;
            fieldErrors?: {
                [key: string]: string;
            };
            /** @description Eco de X-Request-Id (o generado por el servidor) */
            requestId: string;
            retryable?: boolean;
        };
        MeDto: {
            /** Format: uuid */
            id: string;
            /** @example es-AR */
            locale: string;
            /** @example America/Argentina/Buenos_Aires */
            timezone: string;
            /** @description Código de moneda preferida; null si no se eligió */
            preferredCurrencyCode: string | null;
            /** @description Calculado por billeteras activas (docs/spec/06 §2) */
            onboardingCompleted: boolean;
        };
        WalletDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            type: "CASH" | "DEBIT" | "CREDIT";
            /**
             * Format: uuid
             * @description null para CASH; obligatorio en DEBIT/CREDIT
             */
            bankId: string | null;
            locationText: string | null;
            /** @enum {string} */
            status: "ACTIVE" | "ARCHIVED";
            /** @description Monedas habilitadas (mínimo una para activar) */
            currencies: string[];
            version: number;
        };
        WalletListDto: {
            items: components["schemas"]["WalletDto"][];
            /** @description Cursor estable para la página siguiente */
            nextCursor: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto"];
                };
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    MeController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
            /** @description Aún sin implementar (Fase 1) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    WalletsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletListDto"];
                };
            };
            /** @description Aún sin implementar (Fase 2) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    WalletsController_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Mismo key+payload devuelve el resultado previo; payload distinto => 409 IDEMPOTENCY_CONFLICT */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletDto"];
                };
            };
            /** @description Aún sin implementar (Fase 2) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
}
